service: default

runtime: java
entrypoint: java -noverify -jar DemoShopData-0.0.1-SNAPSHOT.war
env: flex

runtime_config:
  jdk: openjdk11

handlers:
  - url: /.*
    script: this field is required, but ignored